name: Build, Test and Deploy Postgram

on:
    push:
        branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Injecting environment vars
          run: |
            echo "SECRET_KEY=test_foo
            DATABASE_NAME=test_coredb
            DATABASE_USER=test_core
            DATABASE_PASSWORD=12345678
            DATABASE_HOST=test_postgram_db
            DATABASE_PORT=5432
            POSTGRES_USER=test_core
            POSTGRES_PASSWORD=12345678
            POSTGRES_DB=test_coredb
            ENV=TESTING
            DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost
                    " >> .env
        - name: Build containers
          run: |
            docker-compose up -d --build
        # - name: Running Tests
        #   run: | 
          #     docker-compose exec -T api pytest

  deploy:
    name: Deploying on EC2 via SSH
    if: ${{ github.event_name == 'push' }}
    needs: [build-test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploying Application on EC2
        uses: appleboy/ssh-action@master
        with:
          host: "yes_host"
          username: "yes_username"
          key: "yes_key"
          passphrase: "yes_passphrase"
          script: |
            cd ~/.scripts
            ./docker-ec2-deploy.sh

# ${{ secrets.POSTGRAM_API_EC2_IP }}
# ${{ secrets.POSTGRAM_API_EC2_USERNAME }}
# ${{ secrets.POSTGRAM_API_SSH_KEY }}
# ${{ secrets.POSTGRAM_API_PASSHPRASE }}